# Generated by Django 4.0.1 on 2022-02-25 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='nftmodel',
            table='nft',
        ),
    ]
