# Generated by Django 4.0.1 on 2022-02-24 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_remove_nftmodel_description_remove_nftmodel_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nftmodel',
            options={'ordering': ('name',), 'verbose_name': 'Nft', 'verbose_name_plural': 'Nft'},
        ),
        migrations.RemoveField(
            model_name='nftmodel',
            name='author',
        ),
        migrations.RemoveField(
            model_name='nftmodel',
            name='price',
        ),
        migrations.RemoveField(
            model_name='nftmodel',
            name='year_of_production',
        ),
    ]
