# Generated by Django 4.0.1 on 2022-02-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0002_alter_nftmodel_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftmodel',
            name='author',
        ),
    ]
