# Generated by Django 4.0.1 on 2022-02-25 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0003_remove_nftmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftmodel',
            name='id',
        ),
        migrations.AddField(
            model_name='nftmodel',
            name='author',
            field=models.OneToOneField(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='nft.nftauthor'),
        ),
    ]
