# Generated by Django 4.0.1 on 2022-02-25 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0004_remove_nftmodel_id_nftmodel_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nftmodel',
            name='author',
        ),
        migrations.AddField(
            model_name='nftmodel',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NftAuthorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nft.nftauthor')),
                ('nft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nft.nftmodel')),
            ],
            options={
                'db_table': 'temp',
            },
        ),
    ]
