# Generated by Django 4.0.1 on 2022-03-12 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nft', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestmodel',
            name='status',
            field=models.CharField(default='CREATE', max_length=20),
        ),
        migrations.AlterField(
            model_name='requestmodel',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='nft.nftauthor'),
        ),
    ]
